package com.zmannotes.spring.mybatis.dao;

import com.zmannotes.spring.mybatis.domain.Stock;

public interface StockMapper {

    int deleteByPrimaryKey(String code);

    int insert(Stock record);


    Stock selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed May 04 22:00:31 CST 2016
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed May 04 22:00:31 CST 2016
     */
    int updateByPrimaryKey(Stock record);
}